# Generated by Django 5.2.14 on 2026-05-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('breed', models.CharField(max_length=100, verbose_name='Raza')),
                ('age', models.IntegerField(verbose_name='Edad (meses)')),
                ('size', models.CharField(choices=[('small', 'Pequeño'), ('medium', 'Mediano'), ('large', 'Grande')], max_length=10, verbose_name='Tamaño')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('vaccinated', models.BooleanField(default=False, verbose_name='Vacunado')),
                ('adopted', models.BooleanField(default=False, verbose_name='Adoptado')),
                ('energy', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='Energía')),
                ('gender', models.CharField(choices=[('male', 'Macho'), ('female', 'Hembra')], max_length=10, verbose_name='Género')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perrito',
                'verbose_name_plural': 'Perritos',
                'ordering': ['name'],
            },
        ),
    ]
