# Generated by Django 5.2.14 on 2026-05-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perritos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Raza', models.CharField(max_length=100)),
                ('Edad', models.IntegerField()),
                ('Tamaño', models.CharField(choices=[('Small', 'Pequeño'), ('Medium', 'Mediano'), ('Large', 'Grande')], max_length=10)),
                ('Pedo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Color', models.CharField(max_length=100)),
                ('Vacunado', models.BooleanField()),
                ('Adoptado', models.BooleanField()),
                ('Energia', models.CharField(choices=[('Low', 'Baja'), ('Medium', 'Media'), ('High', 'Alta'), ('VeryHigh', 'Muy Alta')], default='Medium', max_length=10)),
                ('Genero', models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
