# Generated by Django 5.2.14 on 2026-05-27 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perritos', '0002_perrito_delete_dog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perrito',
            old_name='Pedo',
            new_name='Peso',
        ),
    ]
