# Generated by Django 5.2.14 on 2026-05-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Product_1',
        ),
    ]
